swagger: '2.0'
info:
  title: Json Server API
  description: This is a test swagger file.
  version: '1.0'
host: localhost:3000
schemes:
  - http

tags:
  - name: 讀取接口
    description: 定義讀取資料 API  
  - name: 寫入接口
    description: 定義寫入資料 API  
paths:
  /user:
    get:
      tags:
        - "讀取接口"
      summary: 讀取使用者列表
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/UserList"
        500:
          description: Server Error    
    post:
      tags:
        - "寫入接口"
      summary: 新增使用者
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: body
          description: 使用者資料
          required: true 
          schema:
            $ref: "#/definitions/UserData"
      produces:
        - "application/json"
      responses:
        201:
          description: 使用者新增成功
          schema:
            $ref: "#/definitions/User"
        500:
          description: Server Error    
      deprecated: false
  /user/{userId}: 
    get:
      tags:
        - "讀取接口"
      summary: 依照使用者 Id 讀取該使用者資料  
      parameters:
        - in: path
          name: userId
          description: 使用者 id
          type: integer
          required: true
      produces:
        - "application/json"
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/User"  
    delete:
      tags:
        - "寫入接口"
      summary: 依照使用者 Id 刪除該使用者資料  
      parameters:
        - in: path
          name: userId
          description: 使用者 id
          type: integer
          required: true
      responses:
        200:
          description: ok         
    patch:
      tags:
        - "寫入接口"
      summary: 依照使用者 Id 修改該使用者資料  
      consumes:
        - "application/json"
      parameters:
        - in: path
          name: userId
          description: 使用者 id
          type: integer
          required: true      
        - in: body
          name: body
          description: 使用者資料
          required: true 
          schema:
            $ref: "#/definitions/UserData"
      produces:
        - "application/json"
      responses:
        200:
          description: 使用者修改成功
          schema:
            $ref: "#/definitions/User"
        500:
          description: Server Error    
      deprecated: false    
            
definitions:
  UserList:
    type: array
    items: 
      $ref: "#/definitions/User"
  User:
    description: 使用者資料庫資料
    type: object
    properties: 
      id:
        type: integer
        description: 使用者 id
      title:
        type: string
        description: 使用者標題
      content:
        type: string
        description: 使用者內容
  UserData:
    description: 使用者輸入資料
    type: object
    properties: 
      title:
        type: string
        description: 使用者標題
      content:
        type: string
        description: 使用者內容
  